### ISSUE TITLE
[BUG] Chess: En Passant isn't explained correctly in the tooltip.

### ISSUE THREAD

**Issue by Dqu1J** [legoatoom/GameBlocks#4]
**Describe the bug**
In Chess, the En Passant move isn't explained correctly in one part of the tooltip description. 
The part of that string that has issues is `The pawn can be taken as if it had advanced only one square.`, but that doesn't make sense at all. It should be either removed or described differently.
The actual thing that this should describe is: https://user-images.githubusercontent.com/27054231/150660065-2dcdbd31-0d04-4446-8fb4-a114a8287d7a.mov
But that shouldn't be even typed out, as it isn't really related.
The string is `game.chess.action.tooltip.detail.en_passant`. 

**Expected behaviour**
I suggest 2 fixes: Either remove that part from the string, or describe it more correctly.

**Comment by legoatoom** [comment]
The text is fine, i could replace `taken` with `captured`;
> The result is the same as if the pawn had advanced only one square and the enemy pawn had captured it normally.
> - Wiki https://en.wikipedia.org/wiki/En_passant

**Comment by Dqu1J** [comment]
Something like `Afterwards, the pawn can be captured by the enemy, the result is the same as if it had advanced only one square` would be more descriptive
